version: 2.1
jobs:
  build-check:
    docker:
      - image: cibuilds/hugo:0.62
    working_directory: ~/n0tr00teuorg.gitlab.io
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: hugo -v --gc
      - run: mv public docs
      - run: htmlproofer docs --check-html --allow-hash-href --empty-alt-ignore --disable-external

workflows:
  build-check-exampleSite:
    jobs:
      - build-check
